services:
  postgres:
    image: postgres:17
    container_name: Excelmind_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: Excelmind
    ports: ["5433:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    env_file: .env
    ports: ["4000:4000"]
    depends_on: [postgres]
    volumes:
      - uploads:/app/uploads
  frontend:
    build: ./frontend
    env_file: .env
    ports: ["3000:3000"]
    depends_on: [backend]
volumes:
  postgres_data:
    driver: local
  uploads:
